import 'custom_text_field_sanitized_and_checked_using_a_black_list_Mobile_part_of_the_test.dart' as custom_text_field_sanitized_and_checked_using_a_black_list_Mobile_part_of_the_test;
// ignore: library_prefixes
import 'session_file_name_mobile_platforms_As_a_widget_test_runs_on_Windows_even_if_Android_is_specified_as_device_test.dart' as session_file_name_mobile_platforms_As_a_widget_test_runs_on_Windows_even_if_Android_is_specified_as_device_test;

void main() {
  session_file_name_mobile_platforms_As_a_widget_test_runs_on_Windows_even_if_Android_is_specified_as_device_test.main();
  custom_text_field_sanitized_and_checked_using_a_black_list_Mobile_part_of_the_test.main();
}